backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
        hint: A cool title for the article

      - label: Description
        name: description
        required: true
        widget: string
        hint: A short description, also used for meta fields.

      - label: Category
        name: category
        required: true
        widget: relation
        hint: Select a category
        collection: categories
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: "{{slug}}"
        multiple: false
        optionsLength: 20

      - label: Cover Image
        name: cover
        required: false
        widget: image
        hint: Add an optional cover image
        allow_multiple: false

      - label: Show Cover Image
        name: showCover
        required: false
        widget: boolean
        hint: Check if cover image should be shown on web page

      - label: Published Date
        name: publishedAt
        required: true
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: HH:mm

      - label: Updated Date
        name: updatedAt
        required: true
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: HH:mm

      - label: Content
        name: body
        required: true
        widget: markdown
        buttons: []
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - label: "Page Layout"
        name: "page_layout"
        widget: "list"
        types:
         - label: "Body Section"
           name: "body_section"
           widget: "object"
           fields:
             - { label: "Body Updated", name: "body_updated", widget: "string" }
         - label: "Left Align"
           name: "left_align"
           widget: "object"
           fields:
             - { label: "Left Align Image", name: "left_align_image", widget: "image" }
             - { label: "Left Align Title", name: "left_align_title", widget: "string" }
             - { label: "Left Align Body", name: "left_align_body", widget: "markdown" }
             - { label: "Left Align Link", name: "left_align_link", widget: "string" }

  - name: categories
    label: Categories
    folder: content/categories
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
  - name: "rups"
    label: "Project"
    folder: "content/rups"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "text" }
      - { name: "image", label: "Gambar", widget: "image" }
      - { name: "category", label: "Kategori", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "body", label: "Isi", widget: "markdown" }
      - { name: "date", label: "Tanggal", widget: "datetime" }
