backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
        hint: A cool title for the article

      - label: Description
        name: description
        required: true
        widget: string
        hint: A short description, also used for meta fields.

      - label: Category
        name: category
        required: true
        widget: relation
        hint: Select a category
        collection: categories
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: "{{slug}}"
        multiple: false
        optionsLength: 20

      - label: Cover Image
        name: cover
        required: false
        widget: image
        hint: Add an optional cover image
        allow_multiple: false

      - label: Show Cover Image
        name: showCover
        required: false
        widget: boolean
        hint: Check if cover image should be shown on web page

      - label: Published Date
        name: publishedAt
        required: true
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: HH:mm

      - label: Updated Date
        name: updatedAt
        required: true
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: HH:mm

      - label: Content
        name: body
        required: true
        widget: markdown
        buttons: []
        
        
          
  - name: categories
    label: Categories
    folder: content/categories
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
  - name: "rups"
    label: "Project"
    folder: "content/rups"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "text" }
      - { name: "image", label: "Gambar", widget: "image" }
      - { name: "category", label: "Kategori", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "body", label: "Isi", widget: "markdown" }
      - { name: "date", label: "Tanggal", widget: "datetime" }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
           - {label: Name, name: name, widget: string, default: "Emmet"}
          - {label: Avatar, name: avatar, widget: image, default: "/img/emmet.jpg"}
         
